---
- name: Download Passenger modules
  get_url: url=https://codeload.github.com/phusion/passenger/tar.gz/release-{{ nginx.passenger.version }} dest=/opt/passenger.tar.gz

- name: Unzip Passenger Tar
  unarchive: src=/opt/passenger.tar.gz dest=/opt/ copy=no

- include: sudoers.yml

- name: Change Directory & Configure Passenger
  shell: ./configure --user=www-data --group=www-data --prefix=/opt/nginx --sbin-path=/usr/sbin --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --lock-path=/var/run/nginx.lock --pid-path=/var/run/nginx.pid --with-http_geoip_module --with-http_gzip_static_module --with-http_realip_module --with-http_stub_status_module --with-http_ssl_module --with-http_sub_module --with-http_xslt_module --with-ipv6 --with-sha1=/usr/include/openssl --with-md5=/usr/include/openssl --with-mail --with-mail_ssl_module --add-module=modules/ngx_http_auth_pam_module-1.2 --add-module=modules/echo-nginx-module-0.51 --add-module=modules/nginx-upstream-fair --add-module=modules/nginx-dav-ext-module-0.0.3 --add-module=/opt/passenger/ext/nginx chdir=/opt/nginx-{{ nginx.version }}

- name: Create Sites Enabled Directory
  file: path=/etc/nginx/sites-enabled state=directory owner=root group=root
  sudo: yes