---
- name: Create SSL directory
  file: path=/etc/nginx/ssl/ state=directory owner=root group=root
  sudo: yes

- name: Apply ssl site conf file
  template: src=passenger.ssl.site.j2 dest=/etc/nginx/sites-enabled/{{ app_name }} owner=root group=root
  sudo: yes
  when: passenger == "true"

- name: Copy SSL Certs to server
  copy: src={{ nginx.ssl_cert.crt }} dest=/etc/nginx/ssl/ owner=root group=root force=yes
  sudo: yes

- name: Copy SSL Certs to server
  copy: src={{ nginx.ssl_cert.key }} dest=/etc/nginx/ssl/ owner=root group=root force=yes
  sudo: yes
